Template.editCompanyProfile.helpers ({
    company: function() {
    	return Company.findOne(Meteor.userId());
    }
});

function getCompanyProfile() {
	var companyProfile = {};
	companyProfile.name =  $('#company_profile_name').val();
	companyProfile.website =  $('#company_profile_website').val();
	companyProfile.linkedin =  $('#company_profile_linkedin').val();
	companyProfile.twitter =  $('#company_profile_twitter').val();
	// Get wysiwyg HTML code
	companyProfile.description =  $('#company_profile_description').code();
	companyProfile.email =  $('#company_profile_email').val();
	companyProfile.type =  $('#company_profile_type').val();
	return companyProfile;
}

Template.editCompanyProfile.rendered = function() {
	// Show wysiwyg component
	$("#companyForm").bootstrapValidator({ // initialize the plugin
	    excluded: [':disabled'],
	    feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
        },
        live: 'submitted',
        submitButtons: 'button[id="company_form_bsubmit"]', 
        fields: {
            content: {
                validators: {
                    callback: {
                        message: 'The description is required and cannot be empty',
                        callback: function(value, validator, $field) {
                            var code = $('#company_profile_description').code();
                            // <p><br></p> is code generated by Summernote for empty content
                            return (code !== '' && code !== '<p><br></p>');
                        }
                    }
                }
            }, 
            name: {
                validators: {
                        notEmpty: {
                            message: 'The title is required and cannot be empty'
                        }
                    }
            },
            email: {
            	validators: {
                        notEmpty: {
                            message: 'The title is required and cannot be empty'
                        },
                        emailAddress: {
                        message: 'The value is not a valid email address'
                    }
                    }
            }
        }
    }).on('success.form.bv', function(e) {
        // Prevent form submission
        e.preventDefault();
        var companyId = Meteor.userId();
		var companyProfile = getCompanyProfile();
	    Meteor.call('updateCompanyProfile', companyId, companyProfile, Messages.showMessageOk("Company info updated successfully"));
	    Router.go("/company_index");
    }).find('#company_profile_description').summernote({
	    height: 200,
        onkeyup: function() {
            validateEditor();
        },
        onpaste: function() {
            validateEditor();
        }
	});
}

function validateEditor() {
    // Revalidate the content when its value is changed by Summernote
    $('#companyForm').bootstrapValidator('revalidateField', 'content');
    $('#companyForm').bootstrapValidator('revalidateField', 'name');
    $('#companyForm').bootstrapValidator('revalidateField', 'email');
};
